### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter1/course-project-solo_504#2]
## High priority (must-fix)
- [ ] add a structure to your report. It is better to have an introduction that gives the reader some information about the data and your question. 

- [ ] Add a section called analysis, and explain why exactly you chose that specific method of analysis to answer your questions. Why do you think that method of visualization would help you to answer the questions.

- [ ] Just graphs alone do not answer your questions. You need to explain how those visualizations answer your questions. Try explaining the plots.

- [ ] If you are using a method, you need to first explain the method. What do you mean by Correlation Matrix? what kind of correlation did you use and why? Explain it in your report.

- [ ] Your plots don't have a unit. All numerical properties have to have a unit.

- [ ] Printing the dataset alone does not explain the data. You need to add a section called dataset, and explain the data. What are the columns and what do they show?

- [ ] Add a section called conclusion and summarize your findings and analysis method. 

- [ ] There is too much information in your PairPlot. Either find an alternative visualization method or try to explain the plots. There are over 100 plots in your pairplot.

- [ ] You have not used boxplots properly. Boxplots are not being used alone. Also, you have said "Boxplots are not as intuitive as the other graphs shown above, but it communicates a lot of information in its own way". What are the "a lot of information"? you need to explain each plot. Why do you think using this visualization technique will help you to answer the questions?

- [ ] PCA requires data to meed a set of assumptions. Have you checked whether your data meet those assumptions?

- [ ] Why do you think using PCA will help to answer your questions? and which question does it answer? 

- [ ] You have mentioned, "PCA will give us insight on which features are unnecessary". What are the important and also unnecessary features in your data? Explain in your report.

**Comment by waseem-sarwar** [comment]
Please note, that all new updates are in notebook itself in markdown section and README is not fully up-to date. 

**Please consider notebook and its content as final version with these fixes.**

Here is whats done,

1. Proper structure of markdown sections in my notebook and its content are updated.
2. Data Explanation Section is added.
3. Explanation of the plots is added.
4. Explanation of correlation Matirx are added to illustrate the correlation between different variables/features.
5. Explanation of scatter plots are added to illiterate the correlation between different variables/features.
6. Explanation of pair plots are added and number of pair plots are reduced by using only three features combination. Also different set of plots are added in pair plots. 
7. Explanation of Histogram are added where ever necessary.
8. Explanation of Histogram are added where ever necessary.
9. Probability Density function is added for every features to shows the left/right skewness in the dataset. 
10. PCA section is updated with set of assumption, and some of material are rewritten to remove ambiguities. 
11. Conclusion section is added.
